Add functions to help use OCCweb as a file server, including caching
sot/kadi pull request #213
Opened 2021-12-01 21:46 UTC by taldcroft

## Description

This adds a couple of utility functions to facilitate access to files on OCCweb. Both of these handle authentication implicitly and allow specifying either a full URL or a shortened path. 

The shortened path can be either a string or a Path (where the latter makes it easier to chain down directories). The shortened path basically starts at the top of where OCCweb can be viewed as a file server.

## Testing

- [x] Passes unit tests on MacOS
- [x] Functional testing 

### Functional testing

This got a lot of independent testing during developing of #212.

2021-12-02 18:37 UTC, jeanconn commented on kadi/occweb.py
> +    - ``$SKA/data/aspect_authorization/occweb-<user>.cfg``
Nit, but user isn't defined.

2021-12-02 19:01 UTC, taldcroft commented on kadi/occweb.py
> +    - ``$SKA/data/aspect_authorization/occweb-<user>.cfg``
```suggestion
    - ``$SKA/data/aspect_authorization/occweb-<username>.cfg``
```

2021-12-02 19:02 UTC, taldcroft commented on kadi/occweb.py
> +    - ``$SKA/data/aspect_authorization/occweb-<user>.cfg``
Fixed.

2021-12-02 19:14 UTC, jeanconn approved these changes

2021-12-02 19:16 UTC, jeanconn commented
Though actually I just ran the tests and I've got a bunch of warnings on HEAD ska3 flight?
```
kadi/tests/test_occweb.py: 10 warnings
  /proj/sot/ska3/flight/lib/python3.8/site-packages/astropy/utils/data.py:1587: CacheMissingWarning: Remote data cache could not be accessed due to OSError: Intended kadi cache directory cache is actually a file.
    warn(CacheMissingWarning(msg + e.__class__.__name__ + estr))
kadi/tests/test_occweb.py::test_get_occweb_dir[update-str]
  /proj/sot/ska3/flight/lib/python3.8/site-packages/astropy/utils/data.py:1278: CacheMissingWarning: ('Cache directory cannot be read or created (Intended kadi cache directory cache is actually a file.), providing data in temporary file instead.', '/tmp/astropy-download-27411-kt73m9q6')
    warn(CacheMissingWarning(missing_cache, f_name))
```

2021-12-02 19:47 UTC, jeanconn requested changes
Unexpected warnings on the tests.

2021-12-03 18:18 UTC, javierggt approved these changes

2022-01-05 18:17 UTC, taldcroft commented
Closing this, superceded by #212 which further developed these functions.

2022-01-05 18:17 UTC, closed without merging